name: Docker Image CI

on:
  schedule:
    - cron: '0 8 * * 1'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --tag ${{ secrets.DOCKERHUB_USERNAME }}/jelastic-cli:latest
    - name: Push the Docker image
      run: docker push  ${{ secrets.DOCKERHUB_USERNAME }}/jelastic-cli:latest
